-- 코드를 입력하세요
SELECT A.CATEGORY, SUM(B.SALES) AS TOTAL_SALES
FROM BOOK A JOIN
BOOK_SALES B
ON A.BOOK_ID = B.BOOK_ID
WHERE year(SALES_DATE)=2022 AND month(SALES_DATE)=1
GROUP BY CATEGORY
ORDER BY CATEGORY;